"""add_unique_constraints

Revision ID: c6e43f9e7f50
Revises: 9b6785a5e249
Create Date: 2025-12-28 01:26:13.407941

"""
from alembic import op
import sqlalchemy as sa


revision = 'c6e43f9e7f50'
down_revision = '9b6785a5e249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_school_name_country', 'schools', ['name', 'country'])
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'students', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('uq_school_name_country', 'schools', type_='unique')
    # ### end Alembic commands ###

