"""description

Revision ID: 9e9735fef405
Revises: c6e43f9e7f50
Create Date: 2025-12-28 18:51:31.172274

"""
from alembic import op
import sqlalchemy as sa


revision = '9e9735fef405'
down_revision = 'c6e43f9e7f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

